project:
  type: website

website:
  title: "EcotaxaTools Tutorial"
  favicon: ./media/etx-favicon.png
  sidebar:
    style: 'docked'
    search: false
    contents:
      - section: 'Main'
        contents:
          - href: index.qmd
          - href: info_updates-page.qmd
      - section: UVP & Ecopart Data Processing
        contents:
          - href: info_uvp_general-layout.qmd
          - section: Web Export / R Import
            contents:
              - href: export_UVP_ecopart-export.qmd
              - href: import_UVP_ecopart_import.qmd
          - section: Querying Functions
            contents:
              - href: query_all-taxa.qmd
              - href: query_get-all.qmd
          - section: Working with Ecopart Objects
          - section: Analysis Tools
      - section: "Made By:"
        contents:
        - href: https://thealexbarth.github.io
          text: 'Alex Barth'
format:
  html:
    theme: sandstone
    css: styles.css

editor: visual

