project:
  type: website

website:
  title: "Ecotaxa_Tools_Tutorial"
  sidebar:
    style: 'docked'
    contents:
      - section: 'Main'
        contents:
          - href: index.qmd
          - href: info_updates-page.qmd
      - section: 'Importing Data'
        contents:
          - href: import_UVP_ecopart_import.qmd
      - section: "Made By:"
        contents:
        - href: https://thealexbarth.github.io
          text: 'Alex Barth'
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

